### ISSUE TITLE
Great Project, Question about the Collision Tiles

### ISSUE THREAD

**Issue by ghost** [vnen/godot-rpg2d#3]
Hey Vnen, I just want to say thanks for this project. Learned alot with warping, and setting up tilemaps. Appreciate it!  

I just am having some trouble figuring out on your  tilemap, how exactly does the game know that those red tiles are collidable?

![image](https://cloud.githubusercontent.com/assets/10387670/15451786/079d6398-1f8a-11e6-9e06-f565825335b8.png)
 I've looked into the `player.gd` and other scripts but cannot find anything relating to that collision tilemap name layer. Does the tilemap have an internal mechanism that collides with any `tilemap` name of `collision`?

**Comment by vnen** [comment]
If you look at the TileSet properties in the Inspector, you can see that there are Shapes defined for the collision tiles (when you select any TileMap node, there's a "Tile Set" property with a little > on the right, click on that > to see the TileSet properties).

![2016-05-21_23-43-26](https://cloud.githubusercontent.com/assets/5599796/15451854/55ac7fc8-1fae-11e6-8811-7b45582b26b8.png)

I particularly used [Tiled](http://www.mapeditor.org/) for this, but you can do it [directly in Godot too](http://docs.godotengine.org/en/latest/tutorials/2d/using_tilemaps.html#collision).

**Comment by ghost** [comment]
Awww! I see now, I was at that inspector page, but didn't know they had collision / physics bodies :D Thank you so much!
